name: CI

on:
  workflow_call:
  push:
    branches: 
      - 'develop'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
          fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ vars.GO_VERSION }}

    - name: Go Format
      run: gofmt -s -w . && git diff --exit-code

    - name: Go Vet
      run: go vet ./...
        
    - name: Go Tidy
      run: go mod tidy && git diff --exit-code

    - name: Go Mod
      run: go mod download

    - name: Go Mod Verify
      run: go mod verify

    - name: Go Build
      run: go build -o /dev/null -v ./...

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
      with:
          fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
      
    - name: Go Test
      run: go test -v ./...

    - name: Go Benchmark
      run: go test -v -run=- -bench=. -benchtime=1x ./...
          