name: Publish to Docker Hub

on:
  workflow_call:

jobs:
  push_to_registry:
    name: Docker
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    env:
        IMAGE_NAME: "lordmoocow/aoc"
    steps:
      - uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - name: Authenticate
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Get Version
        id: getver
        run: echo "LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)" >> "$GITHUB_OUTPUT"

      - name: Extract Metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            # set latest tag for default branch
            type=raw,value=latest,enable={{is_default_branch}}
            type=semver,pattern={{version}},value=${{ steps.getver.outputs.LATEST_TAG }}
            type=semver,pattern={{major}},value=${{ steps.getver.outputs.LATEST_TAG }}

      - name: Build & Push
        id: push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            "GO_VERSION=${{ vars.GO_VERSION }}"
            "ALPINE_VERSION=${{ vars.ALPINE_VERSION }}"

    #   - name: Generate artifact attestation
    #     uses: actions/attest-build-provenance@v1
    #     with:
    #       subject-name: docker.io/${{ env.IMAGE_NAME}}
    #       subject-digest: ${{ steps.push.outputs.digest }}
    #       push-to-registry: true
